Added dockerignore
seker212/Discord_bot pull request #40
Opened 2021-04-09 20:44 UTC by seker212

Resolves #29

2021-04-09 21:10 UTC, Niewidzialny84 requested changes
Legit but poker folder should be also included for now in .dockerignore

2021-04-09 21:10 UTC, Niewidzialny84 commented on .dockerignore
> +# particular files
Poker folder is also unused

2021-04-10 08:42 UTC, seker212 commented on .dockerignore
> +# particular files
Done

2021-04-10 08:43 UTC, Niewidzialny84 approved these changes
Legit

2021-04-10 08:43 UTC, merged