add queue to ytplayer
seker212/Discord_bot pull request #51
Opened 2021-04-26 19:24 UTC by szyjah

resolve #49

2021-04-26 20:11 UTC, Niewidzialny84 requested changes

2021-04-26 20:11 UTC, Niewidzialny84 commented on ytplayer.py
> +        self.qeueu = []
You misspelled `queue`

2021-04-26 20:11 UTC, Niewidzialny84 commented on ytplayer.py
> +            channel = ctx.message.author.voice.channel
It contains itself in above if

2021-04-26 20:18 UTC, Niewidzialny84 approved these changes
Seems legit

2021-04-26 20:48 UTC, Niewidzialny84 approved these changes
Noice, `shuffle` and `remove` is well appreciated in the music queue

2021-04-27 14:33 UTC, seker212 requested changes
2 suggestions, generally all right

2021-04-27 14:33 UTC, seker212 commented on ytplayer.py
> +            await ctx.send(string)
1) Don't we want to keep it in embed like the rest?
2) Suggestion: Maybe we should print only a few first entries for queue and it's length?

2021-04-27 18:29 UTC, seker212 approved these changes

2021-04-27 18:30 UTC, merged